# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    container_name: zemiticket-app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
